# Generated by Django 4.0.1 on 2022-01-12 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Book Name')),
                ('author', models.CharField(max_length=120, verbose_name='Author')),
                ('price', models.PositiveIntegerField(default=0)),
                ('publisher', models.CharField(max_length=120, verbose_name='Publisher')),
                ('language', models.CharField(max_length=120, verbose_name='language')),
                ('country_of_origin', models.CharField(max_length=120, verbose_name='Country of Origin')),
                ('details', models.CharField(max_length=1000, verbose_name='Details of Book')),
                ('image', models.ImageField(upload_to='book_images')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='admins.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stock_available', models.PositiveIntegerField(default=0, help_text='No: of Books Available')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookstock', to='seller.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockadder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
